[tool.pytest.ini_options]
testpaths = ["tests"]
python_files = "test_*.py"
addopts = "--strict-markers --disable-pytest-warnings"
markers = [
    "model: tests that involve the model itself",
    "inference: tests requiring at least one model registered"
]